### ISSUE TITLE
MUST restart sublime4 after settings changed

### ISSUE THREAD

**Issue by islercn** [sublimelsp/LSP-TexLab#4]
i am not sure it is caused by LSP or LSP-TexLab

after i change LSP-TexLab settings, there will be a pop-up message every time: "Failed to start LSP-TexLab -disabling for this windows for duration of the current session, xxx", but the suggested steps have no effect and i cannot build tex file unless restart sublime

**Comment by rwols** [comment]
What’s your OS?

**Comment by islercn** [comment]
> What’s your OS?

Windows 10 Ent 21H1 19043.985

**Comment by LDAP** [comment]
That may be caused by ST reloading the plugins

**Comment by LDAP** [comment]
Console log:
```
LSP: starting ['D:\\Local_Repositories\\windows-dev-tools\\bins\\node\\node.EXE', 'C:\\Users\\Lucas Alber\\AppData\\Local\\Sublime Text\\Package Storage\\LSP-json\\15.8.0\\language-server\\node_modules\\vscode-json-languageserver\\out\\node\\jsonServerMain.js', '--stdio'] in C:\Program Files\Sublime Text
reloading settings Packages/User/LSP-TexLab.sublime-settings
LSP: applying .sublime-project override for LSP-TexLab
LSP: applying .sublime-project override for LSP-pyright
Unable to start subprocess for LSP-TexLab
Traceback (most recent call last):
  File "C:\Users\Lucas Alber\AppData\Roaming\Sublime Text\Packages\LSP\plugin\core\windows.py", line 326, in start_async
    transport = create_transport(transport_config, cwd, session)
  File "C:\Users\Lucas Alber\AppData\Roaming\Sublime Text\Packages\LSP\plugin\core\transports.py", line 191, in create_transport
    startupinfo = _fixup_startup_args(config.command)
  File "C:\Users\Lucas Alber\AppData\Roaming\Sublime Text\Packages\LSP\plugin\core\transports.py", line 243, in _fixup_startup_args
    executable_arg = args[0]
IndexError: list index out of range

LSP: applying .sublime-project override for LSP-TexLab
LSP: applying .sublime-project override for LSP-pyright
```

**Comment by rwols** [comment]
this could be https://github.com/sublimelsp/LSP/issues/1632 or https://github.com/sublimelsp/LSP/issues/1456

**Comment by rchl** [comment]
I'll assume that it's no longer a problem since a lot has changed - we don't reload all plugins anymore for example.
